version: 1
builder:
  configs:
    - documentation_targets:
      - MMIO
      - SVD
      - SVD2LLDB
    - documentation_targets:
      - SVD2Swift
      custom_documentation_parameters:
      - "--minimum-access-level public"